"""last_modified_at column added in Booking model

Revision ID: 67a02b80465f
Revises: 79af87ed1084
Create Date: 2024-10-20 12:26:59.742949

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "67a02b80465f"
down_revision = "79af87ed1084"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_modified_at", sa.DateTime()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_column("last_modified_at")

    # ### end Alembic commands ###
