"""add vehicle model

Revision ID: 7061651c5b80
Revises: d7c486d34442
Create Date: 2024-10-31 10:30:59.143178

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7061651c5b80"
down_revision = "d7c486d34442"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("seating_capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicles")
    # ### end Alembic commands ###
