"""Create user model

Revision ID: 958d4e4a0cb9
Revises: 
Create Date: 2024-10-17 13:19:32.491223

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "958d4e4a0cb9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("full_name", sa.String(length=280), nullable=False),
        sa.Column(
            "type", sa.Enum("business", "individual", name="usertype"), nullable=False
        ),
        sa.Column("role", sa.Enum("admin", "user", name="userrole"), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
