"""rent_days and amount columns added to Booking model

Revision ID: d7c486d34442
Revises: c8239bc32f5f
Create Date: 2024-10-27 16:01:18.114232

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7c486d34442"
down_revision = "c8239bc32f5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("rent_days", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column("amount", sa.Float(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_column("amount")
        batch_op.drop_column("rent_days")

    # ### end Alembic commands ###
